### Create a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "12-34567"
}

### Invalid creation, missing number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jane Doe"
}

### Invalid creation, missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "1234567890"
}

### Invalid creation, short name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "JD",
  "number": "1234567890"
}

### Invalid creation, short number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "1234567"
}

### Invalid creation, incorrect number format
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "12345678"
}